import Immutable from 'seamless-immutable'

export default Immutable({
  list: {},
  listLoading: false,

  names: {
    'USDT_BTC': 'Bitcoin',
    'BTC_ETH': 'Ethereum',
    'BTC_XRP': 'Ripple',
    'BTC_LTC': 'Litecoin',
    'BTC_SC': 'Siacoin',
    'BTC_BURST': 'Burst',
    'BTC_BTS': 'BitShares',
    'BTC_GAME': 'GameCredits',
    'BTC_ETC': 'Ethereum Classic',
    'BTC_ZEC': 'Zcash',
    'BTC_DGB': 'DigiByte',
    'BTC_FCT': 'Factom',
    'BTC_LBC': 'LBRY Credits',
    'BTC_FLDC': 'FoldingCoin',
    'BTC_STRAT': 'Stratis',
    'BTC_DCR': 'Decred',
    'BTC_DASH': 'Dash',
    'BTC_XMR': 'Monero',
    'BTC_GNT': 'Golem',
    'BTC_XEM': 'NEM',
    'BTC_STR': 'Stellar',
    'BTC_PPC': 'Peercoin',
    'BTC_STEEM': 'STEEM',
    'BTC_VIA': 'Viacoin',
    'BTC_MAID': 'MaidSafeCoin',
    'BTC_ARDR': 'Ardor',
    'BTC_NMC': 'Namecoin',
    'BTC_BTM': 'Bitmark',
    'BTC_REP': 'Augur',
    'BTC_LSK': 'Lisk',
    'BTC_DOGE': 'Dogecoin',
    'BTC_NXT': 'NXT',
    'BTC_BCN': 'Bytecoin',
    'BTC_BCY': 'BitCrystals',
    'BTC_SYS': 'Syscoin',
    'BTC_CLAM': 'CLAMS',
    'BTC_POT': 'PotCoin',
    'BTC_VTC': 'Vertcoin',
    'BTC_AMP': 'Synereo AMP',
    'BTC_EMC2': 'Einsteinium',
    'BTC_XCP': 'Counterparty',
    'BTC_PINK': 'Pinkcoin',
    'BTC_EXP': 'Expanse',
    'BTC_NXC': 'Nexium',
    'BTC_RADS': 'Radium',
    'BTC_OMNI': 'Omni',
    'BTC_BLK': 'BlackCoin',
    'BTC_GRC': 'Gridcoin Research',
    'BTC_NOTE': 'DNotes',
    'BTC_PASC': 'PascalCoin',
    'BTC_NAV': 'NAVCoin',
    'BTC_BELA': 'Belacoin',
    'BTC_SJCX': 'Storjcoin X',
    'BTC_GNO': 'Gnosis',
    'BTC_FLO': 'Florincoin',
    'BTC_NEOS': 'Neoscoin',
    'BTC_VRC': 'VeriCoin',
    'BTC_BTCD': 'BitcoinDark',
    'BTC_XBC': 'BitcoinPlus',
    'BTC_XPM': 'Primecoin',
    'BTC_NAUT': 'Nautiluscoin',
    'BTC_HUC': 'Huntercoin',
    'BTC_RIC': 'Riecoin',
    'BTC_XVC': 'Vcash',
    'BTC_SBD': 'Steem Dollars'
  }

})
